import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const openapi = readFileSync("openapi.yaml", "utf8");
const paths = openapi.split("components:")[0];
assert.match(paths, /operationId: getMedicationContext/);
assert.match(paths, /operationId: getMedicationSummary/);
assert.match(paths, /operationId: getCurrentMedications/);
assert.match(openapi, /functions\/v1\/oauth-authorize/);
assert.match(openapi, /functions\/v1\/oauth-token/);
assert.doesNotMatch(paths, /^\s{4}(post|put|patch|delete):/m, "GPT Action must expose GET only");

const clientFiles = ["index.html", "cloud-sync.js", "push-notifications.js", "config.js"].map((file) => readFileSync(file, "utf8")).join("\n");
assert.match(clientFiles, /autocomplete="one-time-code"/, "PWA must accept the email OTP inside the installed app");
assert.match(clientFiles, /\/auth\/v1\/verify/, "email OTP must be verified with Supabase Auth");
assert.match(clientFiles, /pattern="\[0-9\]\{6,8\}"/, "email OTP input must accept configured 6–8 digit codes");
assert.match(clientFiles, /id="clearSelectedDayBtn"/, "the selected day must have an explicit cleanup action");
assert.match(clientFiles, /queueDelete\("dose"/);
assert.match(clientFiles, /queueDelete\("observation"/);
assert.match(clientFiles, /medicine: \["Madopark Quick", "Madopark Depot"\]/);
assert.match(clientFiles, /time: "23:00", medicine: "Madopark Depot", dose: "100 mg", note: "", independent: true/);
assert.match(clientFiles, /item\.status === "taken" && !isIndependentDose\(item\)/, "independent dose must be excluded from interval calculations");
assert.match(clientFiles, /items\.filter\(\(item\) => !isIndependentDose\(item\)\)/, "independent dose must be excluded from cascading time changes");
assert.match(readFileSync("version.js", "utf8"), /MEDICINKOLL_VERSION = "32"/);
assert.doesNotMatch(clientFiles, /service_role\s*[:=]\s*["'][^"']+/i);
assert.doesNotMatch(clientFiles, /database_password\s*[:=]\s*["'][^"']+/i);
assert.doesNotMatch(clientFiles, /VAPID_PRIVATE_KEY|REMINDER_CRON_SECRET|GPT_OAUTH_CLIENT_SECRET/);
assert.doesNotMatch(openapi, /push_subscriptions|notification_deliveries|dispatch-medication-reminders/, "GPT Action must not expose push administration");
assert.match(readFileSync("supabase/migrations/202608240001_initial_schema.sql", "utf8"), /enable row level security/g);
console.log("Static security checks passed");
